### ISSUE TITLE
Add new operators '=&' and '=|'

### ISSUE THREAD

**Issue by seemantr** [FlexSearch/FlexSearch#26]
Currently in order to force an or comparison on multiword input one has to specify clause type. I am finding that I require or support a lot so thinking about adding =| operator to simplify the syntax.

 line2 = 'test' {clausetype : 'or'}
Can be rewritten as
line2 =| 'test'

**Comment by Enielezi** [comment]
Hi Seemant

Just thought I'd say hi after such long time. Hope you are doing well.

All the best

Eni

--- Original Message ---
