### ISSUE TITLE
Index Creation

### ISSUE THREAD

**Issue by llongenberger** [FlexSearch/FlexSearch#32]
Can you please provide documentation on the basics of creating an index and crawling files for indexation?

**Comment by seemantr** [comment]
@llongenberger thanks for getting in touch. I am currently working on very detailed documentation along with easy to follow tutorials. We have also added a demo index for people to get started with. Everything is in pipeline and will be released on 7th September 2015 (I have taken time off from work to push all this so it will be there).

For the time being I can point you to http://flexsearch.net/docs/rest/index-management-apis/.This documentation is the most up to date that I have for the moment. Also can you please use the latest version from the ci server as the one on release page is out of date. https://ci.appveyor.com/project/seemantr/flexsearch

Now to answer the second part of your question:.Indexing can be done through the web service or using plugins. FlexSearch ships with two data connectors out of box: SQL and CSV. It if very easy to write your own. You have to implement an interface and put the dll in a folder.

The documentation for indexing can be accessed from http://flexsearch.net/docs/rest/document-management-apis/ 

Please don't hesitate to get in touch regarding any other information you need.
