### ISSUE TITLE
RealTimeSearchers aren't explicitly closed/disposed

### ISSUE THREAD

**Issue by vladnega** [FlexSearch/FlexSearch#43]
When searching using the `Searcher.search` method, we aren't explicitly disposing the acquired `RealTimeSearcher`s. This can cause memory leaks, or increase memory consumption.

The `RealTimeSearcher` uses Lucene's `SearcherManager.acquire()` method to instantiate a new IndexSearcher. In order to release it, the `Dispose()` method of `RealTimeSearcher` should be called, or surround the places where it's used in a `use` statement.

Each time we call FlexSearch's `Searcher.search` method, at least one new `RealTimeSearcher` is initialized (for the `state.IndexSearchers` variable). We should dispose of them after we execute the search.

**Comment by seemantr** [comment]
I think we are disposing the state correctly. If you look at the line 233 we dispose the newly created index state after the seq is done returning the results.

```
// Start composing the search results
        let results = 
            seq { 
                for i = searchQuery.Skip to hits.Length - 1 do
                    let hit = hits.[i]
                    let document = state.GetDoc(hit.ShardIndex, hit.Doc)
                    
                    let result = 
                        state
                        |> distinctByFilter document distinctBy
                        |> cutOffFilter hit cutOff
                    match result with
                    | Some(doc) -> yield state |> processDocument (hit, document, highlighterOptions)
                    | None -> ()
              >>>>>>>>>>>>>>  (state :> IDisposable).Dispose()<<<<<<<<<<<<<<<<<<<<<<<<<
            }
        new SearchResults(RecordsReturned = recordsReturned, BestScore = totalDocs.GetMaxScore(), 
                          TotalAvailable = totalAvailable, Documents = results.ToArray())
```

**Comment by vladnega** [comment]
You are right. Didn't spot it. Thanks!
