### ISSUE TITLE
Support For Searching All Fields

### ISSUE THREAD

**Issue by schmalls** [FlexSearch/FlexSearch#52]
I have looked through the documentation and can't find if there is a way to search all fields in the document. On our existing NHibernate.Search implementation we added an AllFieldsBridge which concatenates the values of every field in the object and creates a new field call `*` which is not stored but allows doing queries on all fields in the document. Is this something that could be done through a plugin easily?

**Comment by vladnega** [comment]
Hi @schmalls ,

Thank you for your interest in FlexSearch. The same approach can be taken in FlexSearch using *PreIndex Scripts*.

You will need to create a non-storing field, and on the `preIndex` event concatenate all fields in the newly created one.

[Here](https://flexsearch.net/docs/index/scripting/#scripting/usage) is a link showing how *preIndex* scripts are used.

Let me know if you need more information.

**Comment by schmalls** [comment]
@vladnega Thank you for the quick response. I will have to spend a little time learning F# and then I'll give it a shot. Once I have something working, I'll post it here for others to see.

**Comment by funkyApe** [comment]
@vladnega what do you mean with create a non-storing field?

**Comment by vladnega** [comment]
@funkyApe, I was under the impression that FlexSearch still had a field setting for deciding whether it's *stored* or *not stored*. I double checked in the code and I can see that this option has somehow been removed along the way. Sorry for the confusion.

I will add support over the next few days for having a field that is *not stored*, i.e. it can only be searched, but its contents cannot be retrieved.

In the meantime, the functionality of searching across all fields can be done by concatenating all fields into a normal `Text` field (which is *searchable* and *stored*) using a *PreIndex Script*.

**Comment by vladnega** [comment]
@funkyApe, I've released version [0.8.5](https://github.com/FlexSearch/FlexSearch/releases/tag/0.8.5) of FlexSearch which includes a new Field Type called `SearchOnly`. As the name suggests, it only allows users to search against it, but it doesn't store the data, thus cannot be retrieved/displayed.

**Comment by funkyMonkeyX** [comment]
Hi @vladnega , just tried the new version but it doesn´t work for me. 
http://localhost:9800 is not reachable. Seems that the server is started successfully. How to get it 
to work?
![image](https://cloud.githubusercontent.com/assets/19387321/25471909/66c1d394-2b29-11e7-9a08-34b98bbef8a1.png)

**Comment by vladnega** [comment]
@funkyMonkeyX, I have raised issue #55 with this problem. I should get it fixed today.

**Comment by vladnega** [comment]
@funkyMonkeyX , I have just pushed release [0.8.6](https://github.com/FlexSearch/FlexSearch/releases/tag/0.8.6) that should fix this issue. Could you take a look?

**Comment by funkyMonkeyX** [comment]
so far the version works, but how to configure and use search fields? ^^
I have created a new index with 2 text fields and one search field but cannot find documents with the
search field (tried anyof, like and so on, seems that it returns data only with matchall). 
Where can I define which fields are used by one search field? Is it possible to configure it per field?

**Comment by funkyMonkeyX** [comment]
Is the usage only possible with preSearch scripts?

**Comment by vladnega** [comment]
@funkyMonkeyX , you have to populate the `SearchOnly` field manually. It doesn't automatically merge the values from all fields.

You will have to write a *PreIndex Script* to  merge these values. The below piece of code should work, assuming your index is made of:
* field1 - Text
* field2 - Text
* combo - SearchOnly

```fsharp
module Script

open FlexSearch.Api.Model
open Helpers
open System

let preIndex (document : Document) = 
    let mergedString = 
        document.Fields
        |> Seq.where (fun kv -> kv.Key <> "combo")
        |> Seq.map (fun kv -> kv.Value)
        |> Seq.fold (fun acc value -> acc + " " + value) ""
    
    document.Set("combo", mergedString)
    
    // The above is the equivalent of:
    //document.Set("combo", document.Get("field1") + " " + document.Get("field2"))  
```

Please refer to [this link](https://flexsearch.net/docs/index/scripting/#scripting/pre-index-script) on where to put your `script.fsx` file. Bear in mind you will have to reopen the index in order for FlexSearch to pick up the script.

**Comment by schmalls** [comment]
@vladnega Thank you for the sample code. How does the `document.Set("combo", mergedstring)` actually specify that it is a `SearchOnly` field?

**Comment by vladnega** [comment]
It doesn't specify it's a `SearchOnly` field. The field should have already been created. This script only runs when you index something. It doesn't create the field for you. You create that field using the *Index Management UI* tool. 

![image](https://cloud.githubusercontent.com/assets/4892712/25490957/6169f448-2b66-11e7-9422-e2b9d661ebf0.png)

Check out the Index Management UI section from the [homepage](https://flexsearch.net/) on how to create the fields using the UI.

**Comment by schmalls** [comment]
Ok. That makes much more sense now. It is hard coming from a pure Lucene.NET background to learn how other systems are setup.

**Comment by vladnega** [comment]
Great, @schmalls. Let me know if it works for you so I can close the issue.

**Comment by schmalls** [comment]
I will go ahead and close the issue. I can update later if I have to tweak the code a little.
