### ISSUE TITLE
Problem with performance counters

### ISSUE THREAD

**Issue by cyrebre** [FlexSearch/FlexSearch#58]
Hi,
Since we've installed Flexsearch (very good product so far), we have a lot of performance counter related problems (not the flexsearch's ones, but MS Commerce Server ones, among others)
Looking at the source code I saw a "lodctr / r" that is bugging my old performance counters and I have to rebuild them manually (lot of work) each time.
Would it be possible to add a command switch not to rebuild them ?
Thanks a lot for this good piece of software :)

**Comment by vladnega** [comment]
Hi @cyrebre ,

Great to hear you're using FlexSearch. I've released a new version of FlexSearch in which you can configure whether or not to reset the performance counters. The configuration is held in the `Conf/Config.ini` file, in the `ResetPerformanceCounters` setting. Just set it to `false` if you **don't** want FlexSearch to run `lodctr /r`. 

Bear in mind that not resetting the performance counters might lead to instability when using the `/memory` endpoint.

Let me know if this fixes your issue.

**Comment by cyrebre** [comment]
Hi @vladnega !

Thanks a lot for this release, I'll do some testing this morning.
I'll keep you informed about the potential side effects of this new setting !

Many thanks.
Cyril
